kind: Secret
apiVersion: v1
metadata:
  name: sso-db-credentials
  namespace: rhsso
data:
  password: base64 encoded password # echo -n password | base64
  username: base64 encoded username # echo -n username | base64
type: Opaque



