apiVersion: k8s.keycloak.org/v2alpha1
kind: KeycloakRealmImport
metadata:
  name: myrealm
  namespace: rhsso
spec:
  resources:
    requests:
      memory: 100M
    limits:
      memory: 500M
  keycloakCRName: do313-keycloak
  realm:
    id: myrealm
    realm: myrealm
    displayName: MyRealm Realm
    enabled: false
    registrationAllowed: false
    passwordPolicy: none
    clients:
    - id: example-client
      publicClient: false
      rootUrl: http://example.com/

