apiVersion: project.openshift.io/v1
kind: Project
metadata:
  name: config-project
spec: {}
---
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    app: finance-webapp
    provider: jkube
    version: 1.0.0-SNAPSHOT
    group: com.example
  name: finance-webapp
  namespace: config-project
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    app: finance-webapp
    provider: jkube
    group: com.example
  strategy:
    rollingParams:
      timeoutSeconds: 3600
    type: Rolling
  template:
    metadata:
      labels:
        app: finance-webapp
        provider: jkube
        version: 1.0.0-SNAPSHOT
        group: com.example
      name: finance-webapp
    spec:
      containers:
      - env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: QUARKUS_OIDC_AUTH_SERVER_URL
          value: "https://sso.apps.ocp4.example.com/realms/configsso-realm"
        image: registry.ocp4.example.com:8443/redhattraining/do313-finance-webapp:v1.0
        imagePullPolicy: IfNotPresent
        name: quarkus
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 9779
          name: prometheus
          protocol: TCP
        - containerPort: 8778
          name: jolokia
          protocol: TCP
        securityContext:
          privileged: false
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: /metrics
    prometheus.io/port: "9779"
  labels:
    app: finance-webapp
    provider: jkube
    version: 1.0.0-SNAPSHOT
    group: com.example
  name: finance-webapp
  namespace: config-project
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: finance-webapp
    provider: jkube
    group: com.example
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: finance-webapp
    provider: jkube
    version: 1.0.0-SNAPSHOT
    group: com.example
  name: finance-webapp
  namespace: config-project
spec:
  port:
    targetPort: 8080
  to:
    kind: Service
    name: finance-webapp
---
apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  labels:
    app: do313-keycloak
  name: do313-keycloak
  namespace: rhsso
spec:
  hostname:
    hostname: sso.apps.ocp4.example.com
  http:
    tlsSecret: sso-tls-secret
  instances: 1
  resources:
    limits:
      memory: 500M
    requests:
      memory: 100M
  db:
    usernameSecret:
      name: sso-db-credentials
      key: username
    passwordSecret:
      name: sso-db-credentials
      key: password
    vendor: postgres
    url: 'jdbc:postgresql://sso.lab.example.com/keycloak'
---
kind: Secret
apiVersion: v1
metadata:
  name: sso-db-credentials
  namespace: rhsso
data:
  password: cG9zdGdyZXM=
  username: cG9zdGdyZXM=
type: Opaque
---
kind: Secret
apiVersion: v1
metadata:
  name: sso-tls-secret
  namespace: rhsso
type: kubernetes.io/tls
data:
  ca.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMxakNDQWI2Z0F3SUJBZ0lJUkFuOUs2bWxwSGd3RFFZSktvWklodmNOQVFFTUJRQXdFREVPTUF3R0ExVUUKQXhNRlVrZ2dRMEV3SUJjTk1qUXhNREV4TURrME9USXdXaGdQTWpFeU5EQTVNVGN3T1RRNU1qQmFNQkF4RGpBTQpCZ05WQkFNVEJWSklJRU5CTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUF2M3BJCkRLU0xlWkRvczUxMnN5cVN2WlVzTHR1NGZVTmF5cVNvZG5sZk5iVlBlank2OG1uU0hYb1ExSjdqa21HK0M2bXQKZFR0L2IvcjBrcm41cHRWa1pESDlPL3QwbVlOVnVGNU5GUHhGUTZ3UHRPODBVYTFFNm8yMnVZc09HUGN1SVpueApKRkJMK2wyVW8zWVQzYU5ONm5LZit5dzJHblpsTWZvaERKcDdKZ2FOWTRvZmI4bkhWTVdtanY4dWRBOU9Vbyt3Ck5KdUE3elRWVEY4QUZ1bFlmWmVvK3NMS3Uxbmw0MjcxKzZIQlZ6dm9WWHo4ekNJamZTTXZpdG05c05Ya2RVNTkKMm1LUWF6RnkxUE4waVd3b21mMnErVzlKYXltZ3h2eFdQRk5MRUw3ZEFxTjVwSmNBbEVEWGQrcTl1YlpFdG5GdQorU05pL0I1eUE1ZW4wWjlpS1FJREFRQUJvekl3TURBZEJnTlZIUTRFRmdRVVJsN3BHU3d6Tm9VbXY5VG55NUZpCmgzRjcyYUV3RHdZRFZSMFRBUUgvQkFVd0F3RUIvekFOQmdrcWhraUc5dzBCQVF3RkFBT0NBUUVBTkhnMDFJZEEKRVFOQ1BjQW56QVFmdFhQOU13Zkp1QWYzenZISHZUb1ZpSXF5RU1weGplRU9ySEJiaFdPU1k5NUJNUGJud3p4cgp5T2Z0eHNTMzNhalowYit6Mlh5cU9uZkVKZ0JYeVBRTTBseG9tYUQxRi91QUlHNUcvaE1GRjU1UWlITnlxelErClFVRHdRTTkveWR2SzdtLzYwR3d3eGRrUFNUU1VsRktWVC9kZVZXMFEyN3EvREZTaStEWVBFVGNJeDRESStoL2YKMmNjd2F4YytXb1lCVGdXdmtoV0ZNZnpVaXFSb0lJUFYyTjhKY1lmK2tMZlBEZDgyQ0tKVnBwSm8vYnJES1JyTQo1bWp3R0lIb0lSMTNrSnJINyszOGVuVzRSSnVjZVVDSFBzZVFMVW9YSTFKUGpTZ0NjQlhsR0tXRzgxUXhUamZhClFwMWRHNTVQdXk1ZDNRPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoK
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURGakNDQWY2Z0F3SUJBZ0lJWnBuN3BESjlRL3N3RFFZSktvWklodmNOQVFFTUJRQXdFREVPTUF3R0ExVUUKQXhNRlVrZ2dRMEV3SUJjTk1qUXhNREV4TURrME9USXlXaGdQTWpFeU5EQTVNVGN3T1RRNU1qSmFNQTh4RFRBTApCZ05WQkFNVEJGSklRa3N3Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRRFhGaFNvCmlPOTBUSkFLTE5OQXRmQ2Y4MCtmeERTUmZweDRseWNXTUlwblNTZHFyZGtMbGRmSEJKNGk0SEZ4MVczVlpLVm4KMEpBL29OU0Y4UC9SdXVjcTFMdlprNk9wbHhRSWFGcW1vaWluQnQ4TXZQcHNYSHFWY1NEYlozWlBmbjN4ZG5xYQpCanlVRXdDeEl5T2NYMXBXcmUvRC85aW8veUJSMmtrNjZyLzg5d0ZFN1RHZ1lXb0hxUkdkRlQzZEhLeUV5MUo1Cng4RkdMU3VwTjhlb0t1Mi9OQ3dKaURFbUt5OHFjUHN0UGFTZHRXc0wzcFdUU1NKRll0S3M4d05NUWtMRC8vSisKRGh2MzN4MmtxNmVydDRMWGs5eThMb2J2b0Z1NzlUZzErTzE4b0F1N2Z2MXBhQW12a1hyenE3d1lmTXhzU1RROQpsVnlyeXlpWTM2MnlYdm1GQWdNQkFBR2pjekJ4TUIwR0ExVWREZ1FXQkJRWVZVeEt5ZXhjL0tVbU5wRFJQYTFVCjY1OTY1akFrQmdOVkhSRUVIVEFiZ2hsemMyOHVZWEJ3Y3k1dlkzQTBMbVY0WVcxd2JHVXVZMjl0TUFrR0ExVWQKRXdRQ01BQXdId1lEVlIwakJCZ3dGb0FVUmw3cEdTd3pOb1VtdjlUbnk1RmloM0Y3MmFFd0RRWUpLb1pJaHZjTgpBUUVNQlFBRGdnRUJBR0t5Q005c0cwN1g1T3ZWQ1hPVVV1TUtrK3F6SllVVWw0cDBDMnppaFJtTDRnYUxKeG4wCkh0UUZUb3I0b0NWZC9FdmtsV1lsZHZ5RWhMSVZSV1FQaWhLMlQ0b0tPZndYcjVoYitWbFIzcitGOGdvS20xSCsKa0hpdkxCb1ppT05EQXNJZm96OUE3VkNOUUR2Y3BFM25Pb2hDYjBueGF0V2lOSHJJUWNBVFNITm9naUhGWEhIVwpDeGZDWW9Jb3h6VWQrbnQ5RVlaMVdWWEdLWVBQZ2JYNkpFUXJqODlUMldsb1k2My9iT3BVc0VyWTFtQm9rdzlvCnlpVnZESFNMVDRpNzZtZVdnSVFZUENYd0RnOHV0QVZxS3Exek45TlFKRUhXdFIrcU5kNFlKRUQ0ajdwYzVpcy8KWHVYUW9kOG1SUm53QjI5WldWdFg2a1UwNW1CcXdPYXBSeW89Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KCg==
  tls.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2UUlCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktjd2dnU2pBZ0VBQW9JQkFRRFhGaFNvaU85MFRKQUsKTE5OQXRmQ2Y4MCtmeERTUmZweDRseWNXTUlwblNTZHFyZGtMbGRmSEJKNGk0SEZ4MVczVlpLVm4wSkEvb05TRgo4UC9SdXVjcTFMdlprNk9wbHhRSWFGcW1vaWluQnQ4TXZQcHNYSHFWY1NEYlozWlBmbjN4ZG5xYUJqeVVFd0N4Ckl5T2NYMXBXcmUvRC85aW8veUJSMmtrNjZyLzg5d0ZFN1RHZ1lXb0hxUkdkRlQzZEhLeUV5MUo1eDhGR0xTdXAKTjhlb0t1Mi9OQ3dKaURFbUt5OHFjUHN0UGFTZHRXc0wzcFdUU1NKRll0S3M4d05NUWtMRC8vSitEaHYzM3gyawpxNmVydDRMWGs5eThMb2J2b0Z1NzlUZzErTzE4b0F1N2Z2MXBhQW12a1hyenE3d1lmTXhzU1RROWxWeXJ5eWlZCjM2MnlYdm1GQWdNQkFBRUNnZ0VBUWRKb0VBdVgvQ2RTRFVzYWV6c3lvRUI5cFk4TjUxaXYyZGVvQm9wa1VLZDYKZ0pNalVRQlNRSDJSUjJzWVRKWGNQdW5HRkxjbTdkSHlOK3RBM3BZc0dGZHlCV3ZCTWkwaDNGRFRMUnVEQlZwOAorQkQ5TWh3N0IzRFBkVlY4UjJlV2MwYW16bXdLTGVhQzE3TEJPeUdUSytPZTlJUmZjWmhoODZxeHJtNFl3dmprCnJOK3VCN3VUbzQ3aGh1U0RGOFFvR3VHcFgvQWpRb0N4ZW9STUo5TnpVNE9rZVMyV3N4TkVhMWdYSHZSR3A4NnYKSTFiUEd0cy9mTG8zbXdIYzNPcFk0RWRsWktxcVpiZGpSQlQzaFk1cVhua0pJbXJrTm9tZnlTL2VXdmxlZ242dgpDZkxqRXVnQ1dQcGJnZUNEWkQ2RTA3bDVMM29OYlgxNGg5YzNLM0QrSVFLQmdRRHZHQVNPdWo1ZGk1dWlIb3BKCnlsZmg2Ny9HZXZEN0lqZ1Z1ZTFkRXF4aldPNlU4SndxdjFxM24xYS92dENYRmkzeHRWVFI5dzRaYzViZmsrQXMKbjR1MUxUT2pRc3BlWUpSZEJWWTVtcDl6blNqcmdYbjVaQUcwdXA4bzNFSlh6NjVsdWNndmNFZmVHRXo2YjNIRwpoKzBoQVZnUHBXRWVOR2lUaW5xTFZSSXJyd0tCZ1FEbVMzekVURHNBcG4veFQwbjd4NFV0REU4eHRNbDFWYUx2ClpaRXl4dXdyd01JUlJERW9aYXA4cXJORkN0SkhSaHVuckFpcEpEZHVPQmZkL3Vua2VjU3NTcmc1QlZqK0JTVGIKQnBGdFVkeFMzaEFxKzFmWnptNFJSU1R5N1N0aVhXN1NIS1hLSHZoN29yOFZjbWhBZEtqZ3kzWWlpa1oxdDBXQgpSOGxTSHJPM0N3S0JnRGIrVFQ0TzlIMUx1VFptMCtQNUdKR3NTZVg3TFNaMlRuUWcyY25JbThJV0dIcEZoWVlICmtYUWV3RE5HVG5BUjkrdGFpL0huWTJUVFEyYVZlc0NJeWZlWU9BSmJRSFRJdmhkUFBPL3U4cklDK2dDQlBXN3gKWTdzUUdiK3FPZEE4d3A0L1J4NHlNeldRWFZSVkFkUnFPMDZXSW8wbXV0blpzQndQZy9ROFV2dWRBb0dBSXNSbQpzNlBtakhTV2dERytNNXF0aWwxL1h6dXg1bHJsWEVyekhyMVZUazJ0ZnJuU3lneC9MbzcrdlgraXUwdmtSTzM5CjZMc2sreWpRd1owSVpvdlRtMGMwaExjLzlpbUVwT1JhOUN3Vm5SVVZUOGZlUFcyaXhFeXlCVkswNkFhL0FrMTgKNGdURzhyTmhNYld4ODNrcFBiYTV3UUVySGY1cktkZFNsMmszTEgwQ2dZRUE2MFdubzRybmNkb3JRdGtjQUNWRwpNTE1FRlZBVk1CeVovRlZGV3d0K3F0Nkp3VThhSlhBTDJRbjNCYzQrc1hpWWU1NXRUQ1VON1VsNG1HcDhsTjVxCkM5dmZqNDBYTmRhaHJtSWlsNFA0OVpzbGFiRStFSHkwUnpNN3l5N3NoaksxTXk2T3lEZi84RVREQ0prOE5LMDMKank1RDF6TndmZlphOE51NWJYZ1lNQ2M9Ci0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0KCg==


