apiVersion: k8s.keycloak.org/v2alpha1
kind: KeycloakRealmImport
metadata:
  name: configsso-realm
  namespace: rhsso
spec:
  resources:
    requests:
      memory: 100M
    limits:
      memory: 500M
  keycloakCRName: do313-keycloak
  realm:
    id: review-realm
    realm: review-realm
    displayName: Review Realm
    enabled: true
    clients:
    - id: review-client
      publicClient: true
      redirectUris:
      - http://finance-webapp-review-project.apps.ocp4.example.com/finance/*
    users:
    - username: developer
      firstName: developer
      lastName: developer
      email: developer@example.com
      enabled: true
      credentials:
      - type: password
        value: "redhat"
        temporary: false

