apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: redhat-operators
  namespace: openshift-marketplace
spec:
  displayName: Red Hat Operators
  image: 'registry.redhat.io/redhat/redhat-operator-index:v4.12'
  priority: -100
  publisher: Red Hat
  sourceType: grpc
